name: math-qa
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pip:
      - mistralai
      - chromadb
      - markdown
      - transformers
      - sentencepiece
      - langchain==0.3.12
      - langchain-community==0.3.12
      - langchain-text-splitters
      - langchain-google-genai
      - google-generativeai


# ollama installieren https://ollama.com/download
# ollama serve
# ollama pull nomic-embed-text / ollama pull mxbai-embed-large
# curl http://localhost:11434/api/tags  --> pr√ºfen, welche Modelle geladen sind


  

# conda env create -f environment.yml
# conda activate env_name
# conda env update -f environment.yml --prune
